config/routes.rb
Rails.application.routes.draw do
  root 'users#index'  
  resources :users , except: [ :edit, :new ]

  resources :games do
    collection do
      get 'list'
    end
  end

  get 'home/index'
  

end

app/models/bet.rb
class Bet < ActiveRecord::Base
	belongs_to :game
	belongs_to :winner_by_penalties, class_name: 'Team', foreign_key: 'winner_id'
		
	after_save :nulify_winner_by_penalties
	
	def winner
		return game.team1 if team1_won?
		return game.team2 if team2_won?		
	end

	def draw?
		score_team1 == score_team2
	end

	def team1_won?
		score_team1 > score_team2
	end

	def team2_won?
		score_team1 < score_team2
	end

	def game_number
		game.number
	end

	def stage
		game.stage
	end

	def nulify_winner_by_penalties
		self.winner_by_penalties = nil unless draw?
	end

	def self.initialize_bets stage	
		Game.stage(stage).map do |game|
			Bet.new(game: game, score_team1: 0, score_team2: 0)
		end		
	end
	
	def self.stage stage
		select { |bet| bet.stage == stage }
	end
end

app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :team1, class_name: 'Team', foreign_key: 'team1_id'
	belongs_to :team2, class_name: 'Team', foreign_key: 'team2_id'
	belongs_to :winner_by_penalties, class_name: 'Team', foreign_key: 'winner_id'

	after_update :update_users_points

	def done?
		actual_score_team1.present? && actual_score_team2.present?
	end

	def label
		"#{team1.name} X #{team2.name}"
	end

	def update_users_points
		User.update_points(self)
	end

	def winner
		return team1 if team1_won?
		return team2 if team2_won?		
	end

	def draw?
		actual_score_team1 == actual_score_team2
	end

	def team1_won?
		actual_score_team1 > actual_score_team2
	end

	def team2_won?
		actual_score_team1 < actual_score_team2
	end

	def score_team1
		actual_score_team1.present?? actual_score_team1 : '-'
	end

	def score_team2
		actual_score_team2.present?? actual_score_team2 : '-'
	end
	
	def teams
		[team1, team2]	
	end

	def self.groups_stage
		result = []
		Team::GROUPS.each do |group|
  		result << Game.games(group).map(&:attributes)
  	end
  	result
  end

  def self.stage stage_number
		Game.where(stage: stage_number) 
	end
	
	def self.done_count
		Game.all.map(&:done?).count {|game| game}
	end

	def self.done
		Game.all.map {|g| g if g.done?}.compact
	end

	def self.not_done
		Game.all.map {|g| g unless g.done?}.compact
	end

	def self.next_games
		Game.not_done.sort_by(&:number)[0..3]
	end

	def self.previous_games		 
		Game.done.sort_by(&:updated_at)[Game.done_count - 4..Game.done_count]
	end
end

app/models/team.rb
class Team < ActiveRecord::Base
	GROUPS = %w(A B C D E F G H)
	GROUPS.each do |group|
		scope "group_#{group}".to_sym, -> { where(group: group) }
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name, presence: true
	
	has_many :bets, dependent: :destroy
	belongs_to :champion, class_name: 'Team'
	accepts_nested_attributes_for :bets

	before_create :init_points

	serialize :points, Array

	def init_points
		points << 0
	end

	def update_points game
		bet = bets.where(game: game).first
		new_points = points.last
		
		if guess_outcome?(bet, game)
			new_points = new_points + 3			
			self.correct_outcomes = self.correct_outcomes + 1
		end
		
		if guess_score?(bet, game)
			new_points = new_points + 2
			self.correct_scores = self.correct_scores + 1
		end
		
		if game.stage != 1 && game.draw?
			if bet.draw?
				new_points = new_points + 2 if bet.winner_by_penalties == game.winner_by_penalties
			elsif game.winner_by_penalties == bet.winner
				new_points = new_points + 2
				self.correct_outcomes = self.correct_outcomes + 1
			end
		elsif game.stage != 1 && bet.draw? && bet.winner_by_penalties == game.winner
			new_points = new_points + 2
			self.correct_outcomes = self.correct_outcomes + 1			
		end

		points << new_points

		save
	end

	def current_points
		points.last
	end

	def guess_outcome?(bet, game)
		(bet.winner == game.winner ||  bet.draw? && game.draw?)? true : false
	end

	def guess_score?(bet, game)
		(bet.score_team1 == game.actual_score_team1 && bet.score_team2 == game.actual_score_team2)? true : false
	end

	def correct_outcomes_percent
		correct_outcomes.to_f / Game.done_count
	end

	def correct_scores_percent
		correct_scores.to_f / Game.done_count
	end

	def initialize_stage stage
		self.bets = self.bets + Bet.initialize_bets(stage)
	end

	def bets_by_stage stage
		bets.stage stage
	end

	def has_draws? stage
		bets_by_stage(stage).any? { |bet| bet.draw? && !bet.game.done? }
	end

	def self.update_points game
		User.all.each do |user|
			user.update_points game
		end
	end

	def self.sorted			
		User.all.sort_by{|user| [user.current_points, user.correct_scores]}.reverse
	end

	def self.build_chart_series
		User.all.inject([]){|result, user| result << {name: user.name, data: user.points} } 
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	def index
		@games = Game.all
	end

	def list
		@games = Game.order(:number)
	end

	def show
		@users = User.all
		@game = Game.find(params[:id])
	end

	def edit
		@game = Game.find(params[:id])
	end
	
	def update
		@game = Game.find(params[:game][:id])		
		@game.update(game_params)
	  redirect_to games_path
	end

	private
  def game_params  	
    params.require(:game).permit(:id, :actual_score_team1, :actual_score_team2, :winner_id)    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.sorted
		@games = Game.done.sort_by(&:updated_at)
		@next_games = Game.next_games
		@previous_games = Game.previous_games
		@series = User.build_chart_series
	end

  def new
  	@user = User.new
  end

  def create
	  @user = User.new(user_params)
	  @user.bets = Bet.initialize_bets(1)
	  @user.save
	  redirect_to edit_user_path(@user)
	end

	def edit
		@user = User.find(params[:id])  	
	end

	def update
		@user = User.find(params[:user][:id])		
		@user.update(user_params)
	  redirect_to users_path
	end

	def show
		@user = User.find(params[:id])
	end

	def stage5
		@user = User.find(params[:id])		
	end

	private
  def user_params  	
    params.require(:user).permit(:id, :name, :champion_id, :striker, bets_attributes: [:id, :score_team1, :score_team2, :game_id, :winner_id])    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bet_helper.rb
module BetHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/user_helper.rb
module UserHelper
	def rowspan? users, index
		return true if index == 0 		
		return true if users[index].current_points != users[index - 1].current_points 		
	end

	def row_span_for_score_table users, points
		User.sorted.map { |user| user if  user.current_points == points }.compact.size
	end
end

app/views/games/edit.html.erb
<%= form_for :game, url: game_path(@game), method: :patch do |game_form| %>
	<table class='table table-center'>
		<tr>		  
	  	<%= game_form.hidden_field(:id)%>
	    <td class='img-right'>
	      <%= image_tag("#{@game.team1.img}.png")%>
	    </td>
	    <td class='label-center'>	      
	      <%= game_form.label @game.team1.name %>
	    </td>
	    <td>
	    <%= game_form.select :actual_score_team1, (0..9).to_a, {}, {class: 'select-score'} %> 
	    X  
	    <%= game_form.select :actual_score_team2, (0..9).to_a, {}, {class: 'select-score'} %>
	    </td>
	    <td class='label-center'>
	      <%= game_form.label @game.team2.name %>
	    </td>
	    <td class='img-left'>
	      <%= image_tag("#{@game.team2.img}.png")%>
	    </td>
	     <td class= 'winner'>
        <%= game_form.select :winner_id, @game.teams.collect {|team| [ team.name, team.id ] }, {}, {class: 'span2'}  %>
      </td>      
		</tr>
	</table>

<div align='center'> 
  <%= game_form.submit 'Salvar', class: "btn btn-primary large-button" %>
</div>
<% end %>

<script type="text/javascript">
  $( 'td .select-score' ).on( "change", function () {    
    if ($(this).parent().children('.select-score').first().val() == $(this).parent().children('.select-score').last().val()){       
      $(this).parents('.row').children('.winner').removeClass('hide')
    } else {
      $(this).parents('.row').children('.winner').addClass('hide')
    };
  });
</script>

app/views/games/index.html.erb
<% (0..7).each do |index| %>
  <div class="pull-left group-table">
    <table class='table'>  
      <thead>
        <tr>
          <th colspan="5"><p class="text-center">Grupo <%= @games[6 * index].team1.group %></p></th>
          <th><p class="text-center">Apostas</p></th>
        </tr>
      </thead>
      <tbody>  
        <% @games[6 * index.. 6 * index + 5].sort_by(&:number).each do |game| %>   
          <tr>      
            <td class='img-right'>
              <%= image_tag("#{game.team1.img}.png")%>
            </td>
            <td class='label-center'>
              <%= label_tag game.team1.name %>
            </td>
            <td>      
            <%= game.score_team1%> 
            X  
            <%= game.score_team2 %> 
            </td>
            <td class='label-center'>        
              <%= label_tag game.team2.name %>
            </td>
            <td class='img-left'>
              <%= image_tag("#{game.team2.img}.png")%>
            </td>
            <td>
              <p class='text-center'><%= link_to '', game_path(game), class: 'icon-eye-open' %></p>
            </td>  
          </tr>
        <% end %> 
      </tbody>
    </table> 
  </div>     
<% end %>

<div class="pull-left group-table" align='center'> 
  <h3>Campeão</h3>  
  <h4 class="muted">-</h4>
  <h3>Artilheiro</h3>
  <h4 class="muted">-</h4>  
</div>  

app/views/games/list.html.erb
<table class="table">
	<thead>
    <tr>
      <th>#</th>
      <th>Jogo</th>
      <th>Preenchido</th>
    </tr>
  </thead>
  <tbody>    
    	<% @games.each do |game| %>
	    	<tr>
					<td><%= game.number %></td>
					<td><%= game.done?? game.label : link_to(game.label, edit_game_path(game)) %></td>
					<td><%= game.done?? "OK" : "-" %></td>
				</tr>
			<% end %>    
  </tbody>
	
	
</table>

app/views/games/show.html.erb
<table class='table show-table' align='center'>  
  <thead>
    <tr>
      <th><p>Nome</p></th>
      <th colspan='5'><p class='text-center'>Aposta</p></th>
      
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>                 
			<tr>
				<td><%= user.name %></td>
			  <td class='img-right'>
			    <%= image_tag("#{@game.team1.img}.png")%>
			  </td>
			  <td class='label-center'>
			    <%= label_tag @game.team1.name %>
			  </td>
			  <td>      
			  <%= user.bets.find_by_game_id(@game.id).score_team1 %> 
			  X  
			  <%= user.bets.find_by_game_id(@game.id).score_team2 %> 
			  </td>
			  <td class='label-center'>        
			    <%= label_tag @game.team2.name %>
			  </td>
			  <td class='img-left'>
			    <%= image_tag("#{@game.team2.img}.png")%>
			  </td>
			  <% if @game.stage != 1 && user.bets.find_by_game_id(@game.id).draw? && user.bets.find_by_game_id(@game.id).winner_by_penalties.present?%>
			  	<td>
			  		<i class="icon-star"></i>
			  		<strong><%= user.bets.find_by_game_id(@game.id).winner_by_penalties.name %></strong>
			  	</td>
			  <% end %>			  
			</tr>
		<% end %>      
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WcPredictor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar">
  <div class="navbar-inner">
    <p class="brand"><strong>Bolão Campeão</strong></p>
    <ul class="nav">
      <li><%#= link_to 'Novo Usuário', new_user_path %></li>
      <li><%= link_to 'Placar', users_path %></li>
      <li><%= link_to 'Resultados e Apostas', games_path %></li>     
    </ul>
    <div class='text-right' >
    	<%= image_tag 'Fifa.png', size: '50'%>
    </div>    
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<%= form_for :user, url: user_path(@user), method: :patch, html: {class: "form-inline"} do |user_form| %>
  <%= user_form.hidden_field(:id)%>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited
      this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  
  <% games_number = 0%>
  <% @user.bets.each do |bet| %>
    <% if games_number % 6 == 0  %>
      <div class="pull-left group-table"><table class='table'>  
        <thead>
          <tr>
            <th colspan="4"><h4 class="text-center">Grupo <%= bet.game.team1.group %></h4></th>
          </tr>
        </thead>
        <tbody>               
    <% end %> 
      <tr>
        <%= user_form.fields_for "bets_attributes[]", bet do |bets_form| %>
          <%= bets_form.hidden_field(:id, value: bet.id)%>               
          <%= bets_form.hidden_field(:game_id, value: bet.game.id)%>
          <td class='img-right'>
            <%= image_tag("#{bet.game.team1.img}.png")%>
          </td>
          <td class='label-center'>
            <%= bets_form.label bet.game.team1.name %>
          </td>
          <td>
          <%= bets_form.select :score_team1, (0..9).to_a, {}, {class: 'select-score'} %> 
          X  
          <%= bets_form.select :score_team2, (0..9).to_a, {}, {class: 'select-score'} %>
          </td>
          <td class='label-center'>
            <%= bets_form.label bet.game.team2.name %>
          </td>
          <td class='img-left'>
            <%= image_tag("#{bet.game.team2.img}.png")%>
          </td>       
        <% end %>
      </tr> 
    <% games_number = games_number + 1 %>  
    <% if games_number % 6 == 0  %>          
      </tbody></table></div>
    <% end %>   
  <% end %>

  <div class="pull-left group-table" align='center'>
    <div class="control-group">
      <label class="control-label"><h3>Campeão</h3></label>
        <div class="controls">
          <%= user_form.select :champion_id, Team.all.collect {|team| [ team.name, team.id ] }  %>
        </div>
        <div class="control-group">
         <label class="control-label"><h3>Artilheiro</h3></label>
        <div class="controls">
          <%= user_form.text_field :striker %>          
        </div>
      </div>
    </div>
  </div> 
       
  <div class='clearfix'></div>
  <div align='right'>
    <a href="#myModal" role="button" class="btn large-button" data-toggle="modal">Regras</a>
    <%= user_form.submit 'Salvar', class: "btn btn-primary large-button" %>
  </div>
  
<% end %>

<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Regras da Fase de Grupos</h3>
  </div>
  <div class="modal-body">
    <ol>
      <li>Para cada <strong>resultado</strong> acertado, você ganhará 3 pontos.</li>
      <li>Para cada <strong>placar</strong> acertado, você ganhará 5 pontos.</li>
      <li>Acertando o campeão você ganhará 10 pontos extras.</li>
      <li>Acertando o artilheiro você ganhará 10 pontos extras.</li>
    </ol>    
  </div>
</div>

app/views/users/index.html.erb
<table class='table table-hover show-table' align='center'> 
	<thead>
		<tr>
			<th><p>Posição</p></th>
			<th><p class='text-center'>Nome</p></th>
			<th><p class='text-center'>Pontos</p></th>
			<th><p class='text-center'>Resultados</p></th>
			<th><p class='text-center'>%</p></th>
			<th><p class='text-center'>Placares</p></th>
			<th><p class='text-center'>%</p></th>
			<th><p class='text-center'>Erros</p></th>
			<th><p class='text-center'>Ver aposta</p></th>
			<th><p class='text-center'>Próxima fase</p></th>
		</tr>
	</thead>
	<tbody>
		<% @users.each_with_index do |user, index| %>			
			<tr>
				<% if rowspan? @users, index %>
					<td rowspan=<%= row_span_for_score_table(@users, user.current_points) %>><%= index + 1 %></td>
				<% end %>
				<td><%= user.name %></td>
				<td><p class='text-center'><strong><%= user.points.last %></strong></p></td>
				<td><p class='text-center'><%= user.correct_outcomes %></p></td>
				<td><p class='text-center'><%= (user.correct_outcomes_percent * 100).round 2 %>%</p></td>
				<td><p class='text-center'><%= user.correct_scores %></p></td>
				<td><p class='text-center'><%= (user.correct_scores_percent * 100).round 2 %>%</p></td>
				<td><p class='text-center'><%= Game.done_count - user.correct_outcomes %></p></td>
				<td>
					<p class='text-center'><%= link_to '', user_path(user), class: 'icon-eye-open' %></p>
				</td>
				<td>
					<p class='text-center'><i class='icon-edit'></i>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<div align='center'>
  <a href="#modal-graph" role="button" class="btn large-button btn-primary" data-toggle="modal">Gráfico de desempenho</a>    
</div>
<br>
<div class='text-center'>
	<h5><strong>Próximos Jogos:</strong></h5>
	<ul class="inline">
		<% @next_games.each do |next_game| %>		
	  	<li><%= link_to next_game.label, game_path(next_game) %></li>
	  <% end %>
	</ul>
	
	<h5><strong>Últimos Jogos:</strong></h5>
	<ul class="inline">
	  <% @previous_games.each do |previous_game| %>		
	  	<li><%= link_to previous_game.label, game_path(previous_game) %></li>
	  <% end %>
	</ul>
</div>
<br>
<div align='center'>
	<%= image_tag("wc.png", size: '250')%>
</div>
 
<!-- Modal -->
<div id="modal-graph" class="modal hide fade plot" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"><p class='text-center'>Bolão Campeão </p></h3>
  </div>
  <div class="modal-body" align='center'>    
  </div>
</div>


<script type="text/javascript">
	$( "a.btn" ).on( "click",  setTimeout(function () {


    $('.modal-body').highcharts({
        title: {
            text: 'Desempenho dos jogadores',
            x: -20 //center
        },
				
				tooltip: {
				          valueSuffix: 'pts'
				        },
        xAxis: {
        		title: {
                text: 'Jogos decorridos'
            },
            categories: <%= @games.map(&:label).unshift('Início').to_json.html_safe %>,
            
            labels: { 
							rotation: -60
						}
        },
        yAxis: {
            title: {
                text: 'Pontos'
            },
            plotLines: [{
                value: 0,
                width: 1,
                color: '#808080'
            }],
            floor: 0
        },            
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            borderWidth: 0
        },
        series: <%= @series.to_json.html_safe %>
    });
  }, 3000));
</script>

app/views/users/new.html.erb
<div class="hero-unit" align= 'center'>
<%= form_for :user, url: users_path do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited
      this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="control-group">    
    <h4><%= f.label :nome %></h4>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="controls">
    <%= f.submit 'Salvar', class: "btn btn-primary" %>
  </div>
  
<% end %>
</div>

app/views/users/show.html.erb
<h2 class='text-center'><%= @user.name %></h2>
<% (0..7).each do |index| %>
  <div class="pull-left group-table">
    <table class='table'>  
      <thead>
        <tr>
          <th colspan="5"><h4 class="text-center">Grupo <%= @user.bets[6 * index].game.team1.group %></h4></th>
        </tr>
      </thead>
      <tbody>               
        <% @user.bets[6 * index.. 6 * index + 5].sort_by(&:game_number).each do |bet| %>   
          <tr>      
            <td class='img-right'>
              <%= image_tag("#{bet.game.team1.img}.png")%>
            </td>
            <td class='label-center'>
              <%= label_tag bet.game.team1.name %>
            </td>
            <td>      
            <%= bet.score_team1%> 
            X  
            <%= bet.score_team2 %> 
            </td>
            <td class='label-center'>        
              <%= label_tag bet.game.team2.name %>
            </td>
            <td class='img-left'>
              <%= image_tag("#{bet.game.team2.img}.png")%>
            </td>     
          </tr> 
        <% end %>
      </tbody>
    </table>
  </div>    
<% end %>

<div class="pull-left group-table" align='center'> 
  <h3>Campeão</h3> 
  <%= image_tag("#{@user.champion.img}.png") if @user.champion.present?%>
  <h4 class="muted"><%= @user.champion.name if @user.champion.present?%></h4>
  <h3>Artilheiro</h3>
  <h4 class="muted"><%= @user.striker %></h4>
  <h3>Pontos</h3>  
  <h4 class="muted"><%= @user.points.last %></h4> 
</div>   

app/views/users/stage5.html.erb
<%= form_for :user, url: user_path(@user), method: :patch, html: {class: "form-inline"} do |user_form| %>
  <table class='table table-center'>  
    <thead>
      <tr>
        <th colspan="5"><h4 class="text-center">Final</h4></th>
      </tr>
    </thead>
    <tbody>       
      <%= user_form.hidden_field(:id)%>    
      <% @user.bets_by_stage(5).each do |bet| %>   
        <tr class='row'>
          <%= user_form.fields_for "bets_attributes[]", bet do |bets_form| %>
            <%= bets_form.hidden_field(:id, value: bet.id)%>               
            <%= bets_form.hidden_field(:game_id, value: bet.game.id)%>
            <td class='img-right'>
              <%= image_tag("#{bet.game.team1.img}.png")%>
            </td>
            <td class='label-center'>
              <%= bets_form.label bet.game.team1.name %>
            </td>
            <td>
            <%= bets_form.select :score_team1, (0..9).to_a, {}, {class: 'select-score'} %> 
            X  
            <%= bets_form.select :score_team2, (0..9).to_a, {}, {class: 'select-score'} %>
            </td>
            <td class='label-center'>
              <%= bets_form.label bet.game.team2.name %>
            </td>
            <td class='img-left'>
              <%= image_tag("#{bet.game.team2.img}.png")%>
            </td>
            <td class= 'winner <%= 'hide' unless bet.draw? %>'>
              <%= bets_form.select :winner_id, bet.game.teams.collect {|team| [ team.name, team.id ] }, {}, {class: 'span2'}  %>
            </td>     
          <% end %>
        </tr>      
      <% end %>     
    </tbody>
  </table>
  <br>
  <div align='center'>    
    <%= user_form.submit 'Salvar', class: "btn btn-primary large-button" %>
  </div>
<% end %>

<script type="text/javascript">
  $( 'td .select-score' ).on( "change", function () {    
    if ($(this).parent().children('.select-score').first().val() == $(this).parent().children('.select-score').last().val()){       
      $(this).parents('.row').children('.winner').removeClass('hide')
    } else {
      $(this).parents('.row').children('.winner').addClass('hide')
    };
  });
</script>